{
    {
      name = " Iron Ingot",
      andar = 1,
      index = 1,
      preco = 100,
    },
    {
      name = " Gold Ingot",
      andar = 1,
      index = 2,
      preco = 135,
    },
    {
      name = " Copper Ingot",
      andar = 1,
      index = 3,
      preco = 130,
    },
    {
      name = " Tin Ingot",
      andar = 1,
      index = 4,
      preco = 130,
    },
    {
      name = " Aluminium Ingot",
      andar = 1,
      index = 5,
      preco = 140,
    },
    {
      name = " Lead Ingot",
      andar = 1,
      index = 6,
      preco = 250,
    },
    {
      name = " Osmium Ingot",
      andar = 1,
      index = 7,
      preco = 350,
    },
    {
      name = " Zinc Ingot",
      andar = 1,
      index = 8,
      preco = 125,
    },
    {
      name = " Nickel Ingot",
      andar = 1,
      index = 9,
      preco = 130,
    },
    {
      name = " Platinum Ingot",
      andar = 1,
      index = 10,
      preco = 140,
    },
    {
      name = " Silver Ingot",
      andar = 1,
      index = 11,
      preco = 140,
    },
    {
      name = " Uranium Ingot",
      andar = 1,
      index = 12,
      preco = 150,
    },
    {
      andar = 1,
      name = " Bismuth",
      preco = 240,
    },
    {
      name = " Crimson Iron Ingot",
      andar = 1,
      index = 14,
      preco = 240,
    },
    {
      name = " Azure Silveringot",
      andar = 1,
      index = 15,
      preco = 250,
    },
    {
      name = " Draconium Ingot",
      andar = 1,
      index = 16,
      preco = 280,
    },
    {
      name = " Ender Ingot",
      andar = 1,
      index = 17,
      preco = 2500,
    },
    {
      name = " Enhanced Ender Ingot",
      andar = 1,
      index = 18,
      preco = 10000,
    },
    {
      name = " Hop Graphite Ingot",
      andar = 1,
      index = 19,
      preco = 3500,
    },
    {
      name = " Redstone Ingot",
      andar = 1,
      index = 21,
      preco = 130,
    },
    {
      name = " Fluix-plated Iron Ingot",
      andar = 1,
      index = 22,
      preco = 3000,
    },
    {
      name = " Fluix Steel Ingot",
      andar = 1,
      index = 23,
      preco = 3500,
    },
    {
      name = " Tyrian Steel Ingot",
      andar = 1,
      index = 24,
      preco = 10000,
    },
    {
      name = " Prosperity Ingot",
      andar = 1,
      index = 25,
      preco = 150,
    },
    {
      name = " Inferium Ingot",
      andar = 1,
      index = 26,
      preco = 280,
    },
    {
      name = " Tertium Ingot",
      andar = 1,
      index = 27,
      preco = 1100,
    },
    {
      name = " Prudentium Ingot",
      andar = 1,
      index = 28,
      preco = 4500,
    },
    {
      name = " Imperium Ingot",
      andar = 1,
      index = 29,
      preco = 20000,
    },
    {
      name = " Supremium Ingot",
      andar = 1,
      index = 30,
      preco = 42000,
    },
    {
      name = " Insanium Ingot",
      andar = 1,
      index = 31,
      preco = 160000,
    },
    {
      name = " Eterium Ingot",
      andar = 1,
      index = 32,
      preco = 40000,
    },
    {
      name = " Netherite Ingot",
      andar = 1,
      index = 33,
      preco = 2100,
    },
    {
      name = " Bronze Ingot",
      andar = 1,
      index = 34,
      preco = 250,
    },
    {
      name = " Brass Ingot",
      andar = 1,
      index = 35,
      preco = 250,
    },
    {
      name = " Electrum Ingot",
      andar = 1,
      index = 36,
      preco = 250,
    },
    {
      name = " Invar Ingot",
      andar = 1,
      index = 37,
      preco = 250,
    },
    {
      name = " Constantan Ingot",
      andar = 1,
      index = 38,
      preco = 250,
    },
    {
      name = " Pewter Ingot",
      andar = 1,
      index = 39,
      preco = 150,
    },
    {
      name = " Steel Ingot",
      andar = 1,
      index = 40,
      preco = 520,
    },
    {
      name = " Enderium Ingot",
      andar = 1,
      index = 41,
      preco = 350,
    },
    {
      name = " Lumium Ingot",
      andar = 1,
      index = 42,
      preco = 280,
    },
    {
      name = " Signalum Ingot",
      andar = 1,
      index = 43,
      preco = 250,
    },
    {
      name = " Refined Glowstone Ingot",
      andar = 1,
      index = 44,
      preco = 300,
    },
    {
      name = " Refined Obsidian Ingot",
      andar = 1,
      index = 45,
      preco = 350,
    },
    {
      name = " Redstone Alloy Ingot",
      andar = 1,
      index = 46,
      preco = 200,
    },
    {
      andar = 1,
      name = " Bismuth Brass Ingot",
      preco = 240,
    },
    {
      andar = 1,
      name = " Bismuth Steel Ingot",
      preco = 260,
    },
    {
      andar = 1,
      name = " Manasteel Ingot",
      preco = 150,
    },
    {
      andar = 1,
      name = " Elementium Ingot",
      preco = 350,
    },
    {
      andar = 1,
      name = " Alfsteel Ingot",
      preco = 5000,
    },
    {
      andar = 1,
      name = " Terrasteel Ingot",
      preco = 1900,
    },
    {
      andar = 1,
      name = " Aerialite",
      preco = 3000,
    },
    {
      andar = 1,
      name = " Compressed Iron Ingot",
      preco = 150,
    },
    {
      andar = 1,
      name = " Refined Iron Ingot",
      preco = 150,
    },
    {
      andar = 1,
      name = " Obsidianingot",
      preco = 250,
    },
    {
      andar = 1,
      name = " Blaze Gold Ingot",
      preco = 500,
    },
    {
      andar = 1,
      name = " Starmetal Ingot",
      preco = 200,
    },
    {
      andar = 1,
      name = " Black Iron Ingot",
      preco = 300,
    },
    {
      andar = 1,
      name = " Cyanite Ingot",
      preco = 480,
    },
    {
      andar = 1,
      name = " Crystal Matrix Ingot",
      preco = 7500,
    },
    {
      andar = 1,
      name = " Crystaltine Ingot",
      preco = 3000,
    },
    {
      andar = 1,
      name = " Crimson Steel Ingot",
      preco = 4500,
    },
    {
      andar = 1,
      name = " Coal",
      preco = 80,
    },
    {
      andar = 1,
      name = " Flint",
      preco = 5,
    },
    {
      andar = 1,
      name = " Coke",
      preco = 19,
    },
    {
      andar = 1,
      name = " Nether Quartz",
      preco = 150,
    },
    {
      andar = 1,
      name = " Niter",
      preco = 20,
    },
    {
      andar = 1,
      name = " Fluorite",
      preco = 50,
    },
    {
      andar = 1,
      name = " Sulfur",
      preco = 50,
    },
    {
      andar = 1,
      name = " Prismarine Shard",
      preco = 40,
    },
    {
      andar = 1,
      name = " Prosperity Shard",
      preco = 110,
    },
    {
      andar = 1,
      name = " Prismarine Crystals",
      preco = 50,
    },
    {
      index = 73,
      andar = 1,
      name = " Arcane Crystal",
      preco = 25,
    },
    {
      andar = 1,
      name = " Certus Quartz Crystal",
      preco = 200,
    },
    {
      andar = 1,
      name = " Charged Certus Quartz Crystal",
      preco = 350,
    },
    {
      andar = 1,
      name = " Varnished Certus Quartz",
      preco = 550,
    },
    {
      andar = 1,
      name = " Raw Eterium",
      preco = 10000,
    },
    {
      andar = 1,
      name = " Lapislazuli",
      preco = 112,
    },
    {
      andar = 1,
      name = " Dimensional Shard",
      preco = 500,
    },
    {
      andar = 1,
      name = " Fluix Crystal",
      preco = 400,
    },
    {
      andar = 1,
      name = " Pure Nether Quartz Crystal",
      preco = 210,
    },
    {
      andar = 1,
      name = " Pure Certus Quartz Crystal",
      preco = 210,
    },
    {
      index = 84,
      andar = 1,
      name = " Applied Singularity",
      preco = 5000,
    },
    {
      andar = 1,
      name = " Pure Fluix Crystal",
      preco = 210,
    },
    {
      andar = 1,
      name = " Nether Quartz Dust",
      preco = 180,
    },
    {
      andar = 1,
      name = " Certus Quartz Dust",
      preco = 180,
    },
    {
      andar = 1,
      name = " Sky Stone Dust",
      preco = 180,
    },
    {
      andar = 1,
      name = " Fluix Dust",
      preco = 180,
    },
    {
      andar = 1,
      name = " Flux Dust",
      preco = 250,
    },
    {
      andar = 1,
      name = " Litherite Crystal",
      preco = 2100,
    },
    {
      andar = 1,
      name = " Lonsdaleite Crystal",
      preco = 3000,
    },
    {
      andar = 1,
      name = " Erodium Crystal",
      preco = 4500,
    },
    {
      andar = 1,
      name = " Kyronite Crystal",
      preco = 6000,
    },
    {
      andar = 1,
      name = " Pladium Crystal",
      preco = 10000,
    },
    {
      andar = 1,
      name = " Ionite Crystal",
      preco = 30000,
    },
    {
      andar = 1,
      name = " Aethium Crystal",
      preco = 60000,
    },
    {
      andar = 1,
      name = " Mica",
      preco = 12000,
    },
    {
      andar = 1,
      name = " Glowstone Dust",
      preco = 320,
    },
    {
      andar = 1,
      name = " Redstone Essence",
      preco = 75,
    },
    {
      index = 101,
      andar = 1,
      name = " Awakened Draconium Ingot",
      preco = 215000,
    },
    {
      index = 102,
      andar = 1,
      name = " The Ultimate Ingot",
      preco = 1000000000,
    },
    {
      andar = 1,
      name = " Gaia Spirit Ingot",
      preco = 8900,
    },
    {
      andar = 1,
      name = " Gaia Spirit",
      preco = 1900,
    },
    {
      index = 104,
      andar = 1,
      name = "Arcane Gold Ingot Eidolon",
      preco = 4500,
    },
    {
      andar = 1,
      name = "Arcane Gold Ingot Forbidden And Arcanus",
      preco = 2000,
    },
    {
      andar = 1,
      name = "Runestone",
      preco = 4500,
    },
    {
      andar = 1,
      name = "Dark Runestone",
      preco = 4500,
    },
    {
      andar = 1,
      name = "Rock Crystal Ore",
      preco = 3500,
    },
    {
      andar = 1,
      name = "Eternal Stella",
      preco = 15000,
    },
    {
      andar = 1,
      name = "Xpetrified Orb",
      preco = 500,
    },
    {
      andar = 1,
      name = "Stellarite Piece",
      preco = 13000,
    },
    {
      andar = 1,
      name = "Hop Graphite Dust",
      preco = 3450,
    },
    {
      andar = 1,
      name = "Netherite Scrap",
      preco = 200,
    },
    {
      andar = 1,
      name = "Draconium Dust",
      preco = 380,
    },
    {
      andar = 1,
      name = "Lithium Dust",
      preco = 1570,
    },
    {
      andar = 1,
      name = "Coal Coke",
      preco = 150,
    },
    {
      andar = 1,
      name = "Emerald",
      preco = 140,
    },
    {
      andar = 1,
      name = "Aquamarine",
      preco = 85,
    },
    {
      andar = 1,
      name = "Mana Powder",
      preco = 100,
    },
    {
      andar = 1,
      name = "Mana Pearl",
      preco = 1400,
    },
    {
      andar = 1,
      name = "Mana Diamond",
      preco = 140,
    },
    {
      andar = 1,
      name = "Mana Emerald",
      preco = 100,
    },
    {
      andar = 1,
      name = "Dragonstone",
      preco = 150,
    },
    {
      andar = 1,
      name = "Pixie Dust",
      preco = 1500,
    },
    {
      andar = 2,
      name = "Ultimate Tier Installer",
      preco = 750000,
    },
    {
      andar = 2,
      name = "Elite Tier Installer",
      preco = 50000,
    },
    {
      andar = 2,
      name = "Advanced Tier Installer",
      preco = 25000,
    },
    {
      andar = 2,
      name = "Basic Tier Installer",
      preco = 10000,
    },
    {
      andar = 2,
      name = "Speed Upgrade Mekanism",
      preco = 1500,
    },
    {
      andar = 2,
      name = "Snergy Upgrade Mekanism",
      preco = 1500,
    },
    {
      andar = 2,
      name = "Polonium Pallet",
      preco = 1000000000,
    },
    {
      andar = 2,
      name = "Hdpe Sheet",
      preco = 2000,
    },
    {
      andar = 2,
      name = "Ultimate Control Circuit",
      preco = 20500,
    },
    {
      andar = 2,
      name = "Elite Control Circuit",
      preco = 10200,
    },
    {
      andar = 2,
      name = "Advanced Control Circuit",
      preco = 3100,
    },
    {
      andar = 2,
      name = "Basic Control Circuit",
      preco = 1000,
    },
    {
      andar = 2,
      name = "Atomic Alloy",
      preco = 5000,
    },
    {
      andar = 2,
      name = "Reinforced Alloy",
      preco = 3500,
    },
    {
      andar = 2,
      name = "Infused Alloy",
      preco = 1000,
    },
    {
      andar = 2,
      name = "Pink Slime",
      preco = 1500,
    },
    {
      index = 142,
      andar = 2,
      name = "Advanced Machine Frame",
      preco = 10000,
    },
    {
      andar = 2,
      name = "Supreme Machine Frame",
      preco = 15000,
    },
    {
      andar = 2,
      name = "Simple Machine Frame",
      preco = 4500,
    },
    {
      andar = 2,
      name = "Pity Machine Frame",
      preco = 1500,
    },
    {
      andar = 2,
      name = "Addon: Efficiency Tier2",
      preco = 2500,
    },
    {
      andar = 2,
      name = "Addon: Speed Tier2",
      preco = 2500,
    },
    {
      andar = 2,
      name = "Addon: Processing Tier2",
      preco = 2500,
    },
    {
      andar = 2,
      name = "Addon: Range Tier12",
      preco = 2500,
    },
    {
      andar = 2,
      name = "Plastic Industrial Foregoing",
      preco = 1000,
    },
    {
      andar = 2,
      name = "Treated Wood Planks",
      preco = 75,
    },
    {
      andar = 2,
      name = "Graphene Sheet",
      preco = 3600,
    },
    {
      andar = 2,
      name = "Ether Gas Bucket",
      preco = 3500,
    },
    {
      andar = 2,
      name = "Latex Bucket",
      preco = 1450,
    },
    {
      andar = 2,
      name = "Water Bucket",
      preco = 250,
    },
    {
      andar = 2,
      name = "Pink Sline Bucket",
      preco = 2500,
    },
    {
      andar = 2,
      name = "Lava Bucket",
      preco = 350,
    },
    {
      andar = 2,
      name = "Liquid Meat Bucket",
      preco = 350,
    },
    {
      andar = 2,
      name = "Bucket Of Biodisel",
      preco = 1000,
    },
    {
      andar = 2,
      name = "Gobber Globette",
      preco = 50000,
    },
    {
      andar = 2,
      name = "Nether Gobbler Globette",
      preco = 100000,
    },
    {
      andar = 2,
      name = "End Gobbler Globette",
      preco = 160000,
    },
    {
      andar = 2,
      name = "Gobber Ingot",
      preco = 18000,
    },
    {
      andar = 2,
      name = "Nether Gobber Ingot",
      preco = 36000,
    },
    {
      andar = 2,
      name = "End Gobber Ingot",
      preco = 72000,
    },
    {
      andar = 2,
      name = "Gobber Glob",
      preco = 450000,
    },
    {
      andar = 2,
      name = "Nether Gobber Glob",
      preco = 900000,
    },
    {
      andar = 2,
      name = "End Gobber Glob",
      preco = 1440000,
    },
    {
      andar = 2,
      name = "Draconium Shard",
      preco = 450,
    },
    {
      andar = 2,
      name = "Energixing Rod Starter",
      preco = 1500,
    },
    {
      andar = 2,
      name = "Energixing Rod Basic",
      preco = 5000,
    },
    {
      andar = 2,
      name = "Energixing Rod Hardened",
      preco = 12000,
    },
    {
      andar = 2,
      name = "Energixing Rod Blazing",
      preco = 20000,
    },
    {
      andar = 2,
      name = "Energixing Rod Niotic",
      preco = 35000,
    },
    {
      andar = 2,
      name = "Energixing Rod Spirited",
      preco = 55000,
    },
    {
      andar = 2,
      name = "Energixing Rod Nitro",
      preco = 150000,
    },
    {
      andar = 2,
      name = "Fish",
      preco = 16,
    },
    {
      andar = 2,
      name = "Feather",
      preco = 195,
    },
    {
      andar = 2,
      name = "Chiken Egg",
      preco = 1600,
    },
    {
      andar = 2,
      name = "Squeleton Skull",
      preco = 360,
    },
    {
      andar = 2,
      name = "Ghast Tear",
      preco = 980,
    },
    {
      andar = 2,
      name = "Leather",
      preco = 350,
    },
    {
      andar = 2,
      name = "Gunpowder",
      preco = 56,
    },
    {
      andar = 2,
      name = "Spider Eye",
      preco = 140,
    },
    {
      andar = 2,
      name = "Soul Shard",
      preco = 1500,
    },
    {
      andar = 2,
      name = "Zombie Head",
      preco = 550,
    },
    {
      andar = 2,
      name = "Creeper Head",
      preco = 560,
    },
    {
      andar = 2,
      name = "Whiter Skeleton Skull",
      preco = 350,
    },
    {
      andar = 2,
      name = "Zombie Heart",
      preco = 460,
    },
    {
      andar = 2,
      name = "Shulker Shell",
      preco = 150,
    },
    {
      andar = 2,
      name = "Ink Sac",
      preco = 130,
    },
    {
      andar = 2,
      name = "Blaze Rod",
      preco = 450,
    },
    {
      andar = 2,
      name = "Ender Pearl",
      preco = 970,
    },
    {
      andar = 2,
      name = "Nether Star",
      preco = 1480,
    },
    {
      andar = 2,
      name = "String",
      preco = 35,
    },
    {
      andar = 2,
      name = "Totten Flesh",
      preco = 45,
    },
    {
      andar = 2,
      name = "Bone",
      preco = 45,
    },
    {
      andar = 2,
      name = "Necrotic Bone",
      preco = 50,
    },
    {
      andar = 2,
      name = "Rib Bone",
      preco = 350,
    },
    {
      andar = 2,
      name = "Withered Rib",
      preco = 180,
    },
    {
      andar = 2,
      name = "Crelicerae",
      preco = 150,
    },
    {
      andar = 2,
      name = "Fine Silk",
      preco = 300,
    },
    {
      andar = 2,
      name = "Tattered Cloth",
      preco = 55,
    },
    {
      andar = 2,
      name = "Wraith Heart",
      preco = 300,
    },
    {
      andar = 2,
      name = "Wither Rose",
      preco = 2500,
    },
    {
      andar = 2,
      name = "Witch Hat",
      preco = 100,
    },
    {
      andar = 2,
      name = "Catalyzing Gland",
      preco = 450,
    },
    {
      andar = 2,
      name = "Eye Of The Storm",
      preco = 560,
    },
    {
      andar = 2,
      name = "Zombie Heart Reliquary",
      preco = 150,
    },
    {
      andar = 2,
      name = "Nebulousheart",
      preco = 1970,
    },
    {
      andar = 2,
      name = "Magma Cream",
      preco = 250,
    },
    {
      andar = 2,
      name = "Slimeball",
      preco = 130,
    },
  }
